/**
 * Embeds model/default.glb as a base64 string in a TypeScript module so the default model
 * ships inside the package and loads with zero bundler configuration. The module is only
 * imported dynamically, so it is a separate lazy chunk in every bundler.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'model', 'default.glb');
const out = join(here, '..', 'src', 'model', 'default-model.generated.ts');

const glb = readFileSync(src);
const b64 = glb.toString('base64');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/embed-model.ts from model/default.glb (${glb.byteLength} bytes). Do not edit.\n` +
    `export const DEFAULT_MODEL_BASE64 =\n  '${b64}';\n`,
);
console.log(
  `embedded default.glb (${(glb.byteLength / 1024).toFixed(1)} kB) → src/model/default-model.generated.ts`,
);
